### ISSUE TITLE
Application exits, when database is not reachable

### ISSUE THREAD

**Issue by enter-haken** [enter-haken/storm#1]
### Current behavior

When you start the application with out running the database, the application will exit.

```
$ make run
if [ ! -d deps ]; then mix deps.get; fi
make -C assets
make[1]: Entering directory '/home/gooose/src/enter-haken/storm/assets'
if [ ! -d node_modules ]; then npm install; fi
make[1]: Leaving directory '/home/gooose/src/enter-haken/storm/assets'
mix compile --force --warnings-as-errors
Compiling 41 files (.ex)
Generated storm app
iex -S mix phx.server
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

[info] Elixir.Storm.Db.Supervisor started.
[info] Application storm exited: Storm.Application.start(:normal, []) returned an error: shutdown: failed to start child: Storm.Db.Supervisor
    ** (EXIT) shutdown: failed to start child: Storm.Db.Listen
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, %DBConnection.ConnectionError{message: "tcp connect (localhost:5432): connection refused - :econnrefused", reason: :error, severity: :error}}
                (storm 1.0.0) lib/storm/db/listen.ex:11: Storm.Db.Listen.init/1
                (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
                (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
                (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application storm: Storm.Application.start(:normal, []) returned an error: shutdown: failed to start child: Storm.Db.Supervisor
    ** (EXIT) shutdown: failed to start child: Storm.Db.Listen
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, %DBConnection.ConnectionError{message: "tcp connect (localhost:5432): connection refused - :econnrefused", reason: :error, severity: :error}}
                (storm 1.0.0) lib/storm/db/listen.ex:11: Storm.Db.Listen.init/1
                (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
                (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
                (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
make: *** [Makefile:21: run] Error 1
````

### Expected behavior

On startup, the application will try to connect to the database infinitely.

### Environment

```
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 21)
```

* Operating system: Gentoo

**Comment by enter-haken** [comment]
Check if `depends_on` `condition` can be removed from `docker-compose.yaml`.

> The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.

[Control startup and shutdown order in Compose][1]

[1]: https://docs.docker.com/compose/startup-order/
